version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - exhaustive
    - godot

linters-settings:
  godot:
    scope: toplevel
    capital: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - godot
    - path: cmd/
      linters:
        - godot
